services:
  backend:
    container_name: marketplace-backend
    build:
      context: ./backend
      dockerfile: Marketplace.Api/Dockerfile
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: marketplace-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    container_name: marketplace-pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    depends_on:
      - db
    env_file:
      - .env

  redis:
    container_name: marketplace-redis
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - .env

  minio:
    container_name: marketplace-minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO__AccessKey}
      MINIO_ROOT_PASSWORD: ${MINIO__SecretKey}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    env_file:
      - .env

volumes:
  db_data:
  minio_data: